# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: osx-64
name: nupic.research
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.8
  - pip

  - pip:
      # Install nupic.torch libraries in develop mode.
      # Assume libraries were cloned into ${HOME}/nta folder
      - -e ${HOME}/nta/nupic.torch

      # Install nupic.research in development mode with dev tools extras enabled
      - -e ".[dev]"

      # Install projects extra dependency
      # See `setup.cfg` for available extras.
      # - -e ".[vernon]"
      # - -e ".[imagenet]"
      # - -e ".[gsc]"
      # - -e ".[dendrites]"
      # - -e ".[transformers]"

